error: Remove USE_NORETURN ifdef
The USE_NORETURN was added because gcc was buggy almost 20 years
ago.  This is no longer needed and this patch removes it.

Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>